### ISSUE TITLE
examples/sls: Implement Twilio function using Twilio provider with Serverless Framework

### ISSUE THREAD

**Issue by ulises-jeremias** [nanlabs/devops-reference#52]
Use the following examples as reference:

- [Official Guide](https://www.twilio.com/docs/labs/serverless-toolkit/guides/typescript) that explains how to create Serverless Twilio function using Typescript and Serverless Framework
- Our example using [AWS Lambda with Typescript](https://github.com/nanlabs/devops-reference/tree/main/examples/serverless/serverless-middy)

**Comment by julianpalmerio** [comment]
A bit of information gathered for this topic:

The [Official Guide](https://www.twilio.com/docs/labs/serverless-toolkit/guides/typescript) talks about [Twilio Functions](https://www.twilio.com/docs/serverless/functions-assets/functions) and how to deploy them through [Twilio CLI](https://www.twilio.com/docs/twilio-cli/quickstart). Twilio Functions are part of [Twilio Serverless](https://www.twilio.com/en-us/serverless), which is not the same as Serverless Framework.

Following the [Official Guide](https://www.twilio.com/docs/labs/serverless-toolkit/guides/typescript) we can deploy Twilio Functions locally, debug them and deploy them in Twilio Serverless through this [Twilio Serverless Plugin](https://github.com/twilio-labs/plugin-serverless)
Also following the guide we can use Typescript as runtime.

Regarding the using Serverless Framework to deploy Twilio Functions, it is complicated because there is still not very good support for this in the serverless framework community.

Anyway, we can follow this [guide](https://www.serverless.com/blog/serverless-and-twilio) to deploy Twilio Functions with serverless framework using the Twilio Provider.
To use this provider we need to use The Serverless Framework Plugin: [serverless-twilio-runtime](https://www.npmjs.com/package/@twilio-labs/serverless-twilio-runtime). Here is the git repository with more documentation: [serverless-twilio-runtime (GIT)](https://github.com/twilio-labs/serverless-framework-integration/)

Some of the problems I have encountered are:

- The plugin for Serverless Framework has not been updated for 2 years.

- Twilio provider for Serverless Framework only works with JavaScript as runtime.

- It still does not have local deployment (like serverless-offline).
